-- 1. List the number of films per category.
USE sakila;

SELECT category_id as category, COUNT(film_id) as number_of_films FROM film_category
GROUP BY category_id;
USE sakila;
-- 2. Retrieve the store ID, city, and country for each store
SELECT s.store_id, ci.city, co.country FROM store as s
JOIN address as a
ON s.address_id = a.address_id
JOIN city as ci
ON ci.city_id = a.city_id
JOIN COUNTRY AS co
ON co.country_id = ci.country_ID;

-- 3. Calculate the total revenue generated by each store in dollars.
SELECT st.store_id, sum(pa.amount)
FROM store as st
JOIN customer as cu
ON st.store_id = cu.store_id
JOIN payment as pa
ON cu.customer_id = pa.customer_id
GROUP BY st.store_id;

-- 4. Determine the average running time of films for each category.
SELECT fcat.category_id, AVG(f.length) as average_time
FROM film as f
JOIN film_category as fcat
ON f.film_id = fcat.film_id
GROUP BY fcat.category_id;

-- 5. Identify the film categories with the longest average running time.
SELECT fcat.category_id, AVG(f.length) as average_time
FROM film as f
JOIN film_category as fcat
ON f.film_id = fcat.film_id
GROUP BY fcat.category_id
ORDER BY average_time
LIMIT 5;

-- 6. Display the top 10 most frequently rented movies in descending order.
SELECT inv.film_id, count(inv.film_id) as counts
FROM rental as re
JOIN inventory as inv
ON re.inventory_id = inv.inventory_id
GROUP BY inv.film_id
ORDER BY counts DESC
LIMIT 10;

-- 7. Determine if "Academy Dinosaur" can be rented from Store 1.
SELECT f.title, st.store_id
FROM film as f
JOIN inventory as inv
ON f.film_id = inv.film_id
JOIN store as st
ON inv.store_id = st.store_id
WHERE f.title = 'Academy Dinosaur' AND st.store_id = 1;

-- 8. Provide a list of all distinct film titles, 
-- along with their availability status in the inventory. 
-- Include a column indicating whether each title is 'Available' or 'NOT available.' 
-- Note that there are 42 titles that are not in the inventory, and this information
--  can be obtained using a CASE statement combined with IFNULL."


SELECT 
    f.title,
    inv.film_id,
    r.return_date,
    CASE
        WHEN r.return_date IS NULL THEN 'Not Available'
        ELSE 'Available'
    END AS status
FROM film AS f
JOIN inventory AS inv
    ON f.film_id = inv.film_id
JOIN rental AS r
    ON inv.inventory_id = r.inventory_id;


    




